apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  type: oci
  interval: 31s
  url: oci://ghcr.io/stefanprodan/charts
  insecure: true

#yq e '.spec.insecure = true' -i examples/podinfo-flux/helm/podinfo-source.yaml
