---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  url: oci://ghcr.io/stefanprodan/manifests/podinfo
  ref:
    tag: 6.4.0
  insecure: true

# yq e '.spec.insecure = true' -i examples/podinfo-flux/helm/podinfo-source.yaml
