apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: bigbang
  namespace: bigbang
spec:
  interval: 10m0s
  ref:
    tag: 2.19.2
  url: https://repo1.dso.mil/big-bang/bigbang
status: {}
